import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import GNB from '@/app/components/GNB';
import ClientProvider from './components/ClientProvider';
import './styles/globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Do It!',
  description: 'Generated by create next app',
};


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClientProvider>
          <GNB />
          {children}
        </ClientProvider>
      </body>
    </html>
  );
}
